### ISSUE TITLE
OGG corruption

### ISSUE THREAD

**Issue by rmeissn** [flathub/org.gnome.EasyTAG#10]
The current version from flathub often corrupts ogg files - ffmpeg reports a broken header.
In the original repo, there appears to be a bugfix MR for this issue: https://gitlab.gnome.org/GNOME/easytag/-/merge_requests/8

Would it be possible to include this MR as a patch for the flathub build?

**Comment by X-m7** [comment]
Can you confirm that corruption still happens? We already did include a patch to fix this problem a few months ago: https://github.com/flathub/org.gnome.EasyTAG/pull/8

Either way I will try to get that merge request to apply properly, which it doesn't out of the box due to it being based on master.

**Comment by rmeissn** [comment]
I've used the latest version on flathub and it corrupted my ogg vorbis files.

What I did: 
1. Download the audio track of a video from youtube as a wav file with [TubeConverter](https://flathub.org/de/apps/org.nickvision.tubeconverter)
2. convert that wav file with [FFaudioConverter](https://flathub.org/de/apps/com.github.Bleuzen.FFaudioConverter) to 160kbs ogg vorbis
3. --> checked the ogg file with ffprobe -> everythings fine
4. tagged the file with easytag (usual tags, added a frontcover picture about 900x900px) and wrote these changes to the file
5. --> checked the ogg file with ffprobe -> the file is reported as broken `[ogg @ 0x560abac2c000] Header processing failed: Invalid data found when processing input`
6. tried several programs to rescue the file - in the end, [clementine](https://flathub.org/de/apps/org.clementine_player.Clementine) helped me by converting the ogg file to ogg 160kbs again - other software refused to convert it. After conversion, all the tags were gone
7. tagged the new file with easytag (usual tags, added a frontcover picture about 900x900px) and wrote these changes to the file
8. --> checked the new ogg file with ffprobe -> the file is now sound

I don't know what's the difference between FFaudioConverter and Clementine, but maybe FFaudioConverter uses a newer format that easytag can't handle. As Clementine is rather old, it might stick to an older format. But that's just a thought I had...

I'm able to replicate the situation with plenty of files. 
I didn't try not to use FFaudioConverter in the beginning, but I doubt that it's related to it, as they are using ffmpeg under the hood.
EDIT: See https://github.com/Bleuzen/FFaudioConverter/blob/af088c32fbfb711f2a42866dce751349d913d485/src/ffmpegtask.cpp#L151

**Comment by X-m7** [comment]
Finally figured out a way to get the code in that merge request to compile correctly, you'll find a command to install a test build with the patch here: https://github.com/flathub/org.gnome.EasyTAG/pull/11#issuecomment-1937770233

That said, I tried using the EasyTAG version currently on Flathub, followed the steps you gave, set some tags plus an album image, and running `ffprobe` on the resulting file didn't give my any errors.

Either way, it would be great if you can test the patched version and let me know if it actually does fix your problem or not.

**Comment by rmeissn** [comment]
I've installed your version via `flatpak install --user https://dl.flathub.org/build-repo/81934/org.gnome.EasyTAG.flatpakref` today and tested with various ogg files.
It seems to produce sound files =)

**Comment by rmeissn** [comment]
Just for anyone else, searching for this bug: I've written a simple script that allows to search through a folder and to print out all files that got issues - currently restricted to .ogg files.
```bash
#!/bin/bash

# Function to traverse directories recursively
traverse_directories() {
    local dir="$1"
    local file_extension="$2"

    # Loop through files and directories in the given directory
    for entry in "$dir"/*; do
        if [[ -d "$entry" ]]; then
            # If the entry is a directory, recursively traverse it
            traverse_directories "$entry" "$file_extension"
        elif [[ -f "$entry" && "${entry##*.}" == "$file_extension" ]]; then
            # If the entry is a file with the specified extension
            # Check it using ffprobe
            ffprobe -v error "$entry" >/dev/null 2>&1
            result=$?
            if [[ $result -ne 0 ]]; then
                echo "$entry"
            fi
        fi
    done
}

# Check if the user provided a directory path as argument
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <directory_path>"
    exit 1
fi

directory="$1"

# Check if the provided path is a directory
if [[ ! -d "$directory" ]]; then
    echo "Error: '$directory' is not a directory."
    exit 1
fi

# Call the function to traverse directories
traverse_directories "$directory" "ogg"
```
